apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  key: mongo-root-password
                  name: mongodb-secret
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap  # reference to mongodb-configmap
                  key: database_url # reference to database url value
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-service  # it's random name
spec:
  selector:
    app: mongo-express
  type: LoadBalancer  # assigns service an external IP and so accepts external req. is required to open service. Usually default value is 'Cluster IP'
  ports:
   - protocol: TCP
     port: 8081
     targetPort: 8081
     nodePort: 30000 # port which should be opened so user has an access from browser. must be [30000-32767]

