apiVersion: v1
kind: Secret # usually these files are not saved in repo, but in k8s
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU= # values muse be base-64 encoded!!
  mongo-root-password: cGFzc3dvcmQ=