apiVersion: v1
kind: Secret # usually these files are not saved in repo, but in k8s
metadata:
  name: mysql-secret
  namespace: my-namespace
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ= # values muse be base-64 encoded!!