apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: {{ .Values.webapp.numberOfWebbAppReplicas }}
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      # we need to substitue some yaml here, it was moved to _common-blocks.tpl file
      # previously it was:
      # - name: webapp
      #   image: {{ .Values.do—ÅkerRepoName | lower }}/k8s-fleetman-helm-demo:v1.0.0{{ if .Values.development }}-dev{{ end }}
      # template OR include
      # template example . is to reference from what file to take values. it's too complicated so please . here
      # include can be used with pipeline, so it's preferable to use it
      # use minus before curly brackets to remove extra line
      # if you comment something in curly brackets, it will be executed! Carefully!
      #  template "webappImage" .
      {{- include "webappImageWithoutHardcodedIdentation" . | indent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort
